(ns masyst.cljc.common
  (:require [masyst.cljc.tools :as tools]))

(def absolute-session-timeout (tools/hour->sec 12))
(def idle-session-timeout (tools/min->sec 30))

(def kw->label {:ebs-tree "EBS Struktura"
                :ebs-project "EBS Projekt"
                :ebs-handover "EBS Předávací"
                :ebs-calc "EBS Rozpočet"
                :ebs-offer "EBS Nabídka"
                :ebs-other "EBS Ostatní"
                :ebs-other-category "EBS Ostatní kategorie"
                :ebs-construction-diary "Stavební deník"
                :psg "PSG"
                :user "Uživatel"
                :role "Role"
                :audit "Audit"
                :order "Objednávka"
                :supplier "Dodavatel"
                :cost-center "Středisko"
                :tech-design "Výkres"
                :material "Materál"
                :invoice "Faktury"
                :contract "Smlouvy"
                :other "Ostatní"
                :issue "Požadavky"
                :issue-state "Stavy požadavků"
                :issue-type "Typy požadavků"
                :issue-priority "Priority požadavků"
                :issue-project "Projekty požadavků"
                :country "Státy"
                :crm-subj "CRM Subjekty"
                :crm-event "CRM Události"
                :crm-event-type "CRM Typ události"
                :crm-sale "CRM Prodeje"
                :crm-product "CRM Produkty"
                :crm-project "CRM Projekty"
                :automobile "Automobily"
                :bank-holiday "Státní svátky"
                ;;:vacation "Dovolené"
                ;;:business-trip "Služební cesty"
                :drive-book "Kniha jízd"
                ;;:drive-book-item "Položka knihy jízd"
                :time-sheet "Evidence docházky"
                ;;:time-sheet-item "Položka docházky"
                :approval-status "Schvalování"
                :time-sheet-item-type "Typ záznamu docházky"
                :pasman "Pašmán - Pobytová taxa"
                :expense "Výdaje"})
